Adding haskell and greek lambdas
brain-fuel-co/lambda-cli pull request #1
Opened 2023-03-16 23:22 UTC by donovansmith44

In addition to your original request, I also added the explicit Haskell-style lambdas of (\x -> x) to the grammar. Let me know if you like it.

2023-03-17 01:29 UTC, brain-fuel requested changes

2023-03-17 01:29 UTC, brain-fuel commented on src/lambda_cli/core.clj
> +             | '\\\\' VAR_EXP '->' L_EXP
Might as well just change '\\\\' to LAMBDA. The original intent of my ask was just to make it easier to type in "lambda" in multiple forms. If we're going to have the '->' for separating the binding from the lambda <var> we might as well allow it everywhere.

2023-03-17 01:29 UTC, brain-fuel commented on src/lambda_cli/core.clj
> +             | '\\\\' VAR_EXP '->' L_EXP
Note: In my comment above, I actually typed the characters ' \ \ \ \ ' in order, but they got escaped.

2023-03-18 00:21 UTC, donovansmith44 reviewed
Allowing use of '->' operator everywhere.

2023-03-18 00:27 UTC, donovansmith44 reviewed
Allowed '->' to be used everywhere

2023-03-18 00:28 UTC, donovansmith44 reviewed
Allowed '->' to be used everywhere

2023-03-18 00:50 UTC, donovansmith44 reviewed
Def BINDing of abstractions of vars to L_EXPs

2023-03-18 18:46 UTC, donovansmith44 reviewed
I thought it might be easier to evaluate tree elements if we had keywords for construction rules, which allows for clearer bifurcation and descent.

2023-03-18 23:30 UTC, brain-fuel requested changes

2023-03-18 23:30 UTC, brain-fuel commented on src/lambda_cli/core.clj
> +             | <'('> L_EXP <')'>
Correct with the apply and abstract bits. Technically (and I just looked this up) line 20 is not part of the lambda calculus grammar.

2023-03-18 23:30 UTC, brain-fuel commented on src/lambda_cli/core.clj
> +             | <'('> L_EXP <')'>
Meaning this: <'('> L_EXP <')'>

2023-03-18 23:38 UTC, brain-fuel commented on src/lambda_cli/core.clj
> +             | <'('> L_EXP <')'>
Actually, I was wrong. 

Application is what I have for line 19 (in red)
Abstraction is LAMBDA VAR BIND L_EXP

2023-03-20 19:17 UTC, donovansmith44 reviewed
Fixing APPLY and L_EXP definitions

2023-03-20 19:22 UTC, brain-fuel approved these changes

2023-03-20 19:22 UTC, merged